### ISSUE TITLE
Load from a file pointer instead of filepath string

### ISSUE THREAD

**Issue by Ouwen** [nipy/nibabel#1026]
I was wondering if there is an easy way for file pointers to be supported when loading `nii` files instead of string paths. This would allow loading from memory buffers or streaming data over network.

**Comment by rmarkello** [comment]
Hi @Ouwen ! Most of the main image classes support a `.from_bytes()` method that can be used to load data directly into an image. (Image instances conversely also support a `.to_bytes()` method.) 

For example, the following should work (given you have `img.nii.gz` locally):

```python
>>> import nibabel as nib
>>> img1 = nib.load('img.nii.gz')
>>> img2 = nib.Nifti1Image.from_bytes(img.to_bytes())
>>> np.allclose(img1.dataobj, img2.dataobj)
True
```

Therefore, if you have a file pointer `fp` you should be able to just:

```python
>>> img2 = nib.Nifti1Image.from_bytes(fp.read())
```

Would this functionality address your use case?

**Comment by effigies** [comment]
Should have closed this, but might as well just add that you can (since #1129) load directly from streams with `nb.Nifti1Image.from_stream(fp)`. The stream will need to be uncompressed (so you can pass to `gzip.GzipFile()` if you want first.

It would be good to auto-detect compressed streams in the future...
