### ISSUE TITLE
Array element corruption saving nifti images

### ISSUE THREAD

**Issue by Chris-N-K** [nipy/nibabel#1069]
Hi, I encountered a problem when saving nifti images.

Scenario:
- I have an nifti file of data dtype int16
- I make an label array for the image (just integer values)
- I want to save the label array with the header of the original nifit image

What happens:
If I load the label image back in the header data dtype is int16 like of the original image. The dtype of the dataobj is float64 (accessed via `np.asanyarray(nii.dataobj)`. If I now check the values inside of the array my previous values are altered like  2 -> 2.00007, 3 -> 2.99995 some will stay 4. values.

The reason for that seems to be that the default dtype of a numpy array is float64 if not specifically called. The array dtype does not update the header data dtype. `nii.update_header()` does not update data dtype. If you save the image with a float array and an int data dtype the inconsistencies will occur.

This is  easy to solve by calling `np.round()` before using the reloaded array but will make problems in many programs that expect the images to be integer values and just cast them explicitly to int, just dropping the values after the dot.

Expected behaviour:
I know the error is partly on my side for using a float array for my labels and using the header from the original file.
I think you should get either a warning, that the data types do not match or at least the `update_header()`method should check for equality of array and header data dtype and update accordingly.

How to reproduce:
```Python
import numpy as np
import nibabel as nib

header = nib.Nifti1Header()
header.set_data_dtype(np.int16)
arr = np.random.randint(10, size=(10,10,4)).astype(np.float64)
nii = nib.Nifti1Image(arr, affine=np.diag([1,1,1,1]), header=header)
nii.update_header()
nii.to_filename('/home/user/test.nii')
rl_nii = nib.load('/home/user/test.nii')
print(np.unique(arr))
print(np.unique(rl_nii.dataobj))
print(np.unique(rl_nii.get_fdata()))
```

Best regards,
Chris

**Comment by effigies** [comment]
Saving a floating-point array to int16 is a very common method to compress data, and the approach is to set a slope and intercept so that you get 2**16 steps from the lowest value to the highest value. The idea is that you generally have 7-12 bits of precision from the scanner itself, and will often be stored as 16 bit ints along with scale factors. When working with the data you can recover the scanner values by taking `scl_slope * dataobj + scl_inter`, but you never acquire new bits of precision justifying storing the data as float32 or float64, so you rescale to 16 bits of precision when it's time to save.

This can obviously have some drawbacks when working with integral data, such as labels. However, warning on such a common operation is going to annoy a lot of users.

One thing that might make sense is to respect the intent code `NIFTI_INTENT_LABEL` (1002) and do some extra checks:

```Python
if img.header.get_intent_code('niistring') == 'NIFTI_INTENT_LABEL':
    slope, inter = 1, 0
    if not np.issubdtype(img.header.get_data_dtype(), np.integer):
        warning("Label file to be written with inexact type")
    elif not np.allclose(img.dataobj, np.rint(dataobj)):
        warning("Inexact data to be rounded to nearest integer")
```

**Comment by ch-n** [comment]
Hi thanks for the reply.
I was not aware of this method, thanks for the information. I already suspected that the error was more on my side than on `nibabel`'s. Warnings constantly appearing when not necessary is definitely no good.

The additional checks in case of a declared intent seem reasonable. 
Good that I already declare them as labels, so other applications can directly load them as label maps.

As take home message I will be more cautious with my array dtypes. ^^

Best regards,
Chris
