### ISSUE TITLE
Reorganize/compress test files to reduce package footprint

### ISSUE THREAD

**Issue by neurolabusc** [nipy/nibabel#1087]
It would be great if the file nibabel/nibabel/nicom/tests/data/4d_multiframe_test.dcm could be compressed, similar to several other test files in this folder. The command `pigz -11 -n 4d_multiframe_test.dcm` will reduce the file from 58.8mb to 68kb. This reduces the disk requirements for nibabel.

**Comment by effigies** [comment]
Getting large data files out of the package sounds good. Is `dcm.gz` happily parsed by all parsers, or would we need to decompress it at test time?

We also have test data repositories that we're supposed to be using for these large files, so we can also just move it there and update the test locations.

I assume the concern is with the size of the directory/sdist/wheel, and not the repository itself? Because rewriting history would be a heavier lift.

**Comment by matthew-brett** [comment]
I seem to remember I wasn't worried about that, because git compresses the file down when storing it - and I thought that the 58MB on disk probably wouldn't be an issue.  But - I can see it's a little annoying in the sdist or wheel.

**Comment by Korijn** [comment]
Just adding 2cts: you can also install the package in a fresh virtual environment and run the tests against that. It's not strictly required to include tests in the package in order to be able to run them against an installation.
