### ISSUE TITLE
Load image with non-conforming filename?

### ISSUE THREAD

**Issue by quasarj** [nipy/nibabel#1128]
Is there a way to load a file if it does not end in .nii or .nii.gz?

I have looked through the code and read over the issues, but don't see any info on how to do this. I'm a little afraid that the code looks like nibabel assumes the filenames are accurate, which is... highly dangerous, to say the least. I'm also confused by why it would even do this, because it looks like it also reads some bytes from the file to "sniff" the type?

**Comment by matthew-brett** [comment]
Could you use something like:

```python
with open('test.dat', 'rb') as fobj:
    img = nib.Nifti1Image.from_bytes(fobj.read())
```

?

**Comment by effigies** [comment]
If you're looking for the reasons the code is the way it is, there are several problems we need to solve:

1) Handle images with multiple paired files (`.hdr` + `.img`) and allow users to load the pair by passing either filename
2) Handle image types with multiple possible representations (`.hdr` + `.img` OR `.nii`)
3) Handle multiple image types that share header formats (e.g., Analyze, SPM-style Analyze, NIfTI-1)
4) Handle compression transparently for all of the above
5) Delay loading of data array until called

(2) is the big pain that makes even using `nib.Nifti1Image.from_filename('test.dat')` fail, as trying to determine how to read a NIfTI file automatically requires knowing what variant it is. To override this detection, you can create a `file_map`:

```Python
file_map = nib.Nifti1Image.make_file_map({'image': 'test.dat'})
img = nib.Nifti1Image.from_file_map(file_map)
```

This is somewhat irreducibly complex (in the current architecture) because we have to consider paired images and delayed data loading. It's possible that automatically detecting compression from the magic number instead of from the extension could be done without a lot of rearchitecting.

**Comment by quasarj** [comment]
Thank you for the reply! I had forgotten about the .hdr + .img situation, and I can definitely see how that may add complexity.

And thank you for the idea for overriding the detection. That does work if my .nii file is not compressed, but if it's gzipped I get an error.  Is there some way to tell it to expect it compressed? I only see examples passing the keys "image" and "header" to make_file_map.

**Comment by effigies** [comment]
No. Right now our image openers that store filenames so that you can close and reopen files as needed (I forgot to mention that we try to avoid keeping filehandles open longer than needed, as HPC clusters often have strict quotas) rely on the extension of a gzip-compressed file to be `.gz`. This limitation is what I was trying to get at here:

> It's possible that automatically detecting compression from the magic number instead of from the extension could be done without a lot of rearchitecting.

In any case, right now you've got three options. The quick one follow's Matthew's suggestion:

```Python
import gzip
import nibabel as nib

with gzip.open('test.dat') as fobj:
    img = nib.Nifti1Image.from_bytes(fobj.read())
```

This will load the whole thing into memory in a single shot. The second one will use a `GzipFile`, which maintains an open file object:

```Python
import nibabel as nib
import gzip

fobj = gzip.GzipFile('canary.dat.gz')
file_map = nib.Nifti1Image.make_file_map({'image': fobj})
img = nib.Nifti1Image.from_file_map(file_map)
```

This saves you some memory at the cost of having an open file handle, and one that has no random access. There may be some cases where this is a good tradeoff, but if you have `indexed-gzip` installed, you can get a much better deal:

```Python
import nibabel as nib
import indexed_gzip as igzip

fobj = igzip.IndexedGzipFile('canary.dat.gz')
file_map = nib.Nifti1Image.make_file_map({'image': fobj})
img = nib.Nifti1Image.from_file_map(file_map)
```

In this case, `IndexedGzipFile` will actually do what our `Opener()` objects do and close the file when it's not reading it. It also builds an index during read that makes random access extremely fast. The only downside is that it's not in the stdlib so you need to `pip install indexed-gzip`, but you definitely should.

**Comment by quasarj** [comment]
Ah excellent, thank you! I really appreciate your time. I expect to be using this library for a few projects and this will help greatly. I'll think about what you said as far as trying to detect, and may write a patch at some point if time permits.
