### ISSUE TITLE
Conforming 2D images loses all data

### ISSUE THREAD

**Issue by kabbas570** [nipy/nibabel#1150]
I am trying to resample a nii. file, I am applying transformations below; the voxel dimensions are resampled as I can see from the header information; however, the final resampled file after .get_fdata() has all zeros.

```ruby
import nibabel.processing
import nibabel as nib
img_SA_path=r'C:\My_Data\M2M Data\data\train\001/001'+'_LA_ES.nii.gz'
img_LA_gt =nib.load(img_SA_path)
n1_header = img_LA_gt.header
print(n1_header) 
resample_img = nibabel.processing.conform(img_LA_gt,voxel_size=(1.0, 1.0, 1.0), out_shape=img_LA_gt.shape, order=3, cval=0.0, orientation='RAS')
n2_header = resample_img.header
print(n2_header) 
resample_img = resample_img.get_fdata() ## this now coniatns all zeros
```

**Comment by effigies** [comment]
Hi, are you able to share this data file? It's going to be hard to understand this without.

**Comment by kabbas570** [comment]
> Hi, are you able to share this data file? It's going to be hard to understand this without.

**Comment by effigies** [comment]
I see. Your `001_LA*` images are 2D. The `001_SA*` images conform just fine. The issue is with the `mode` parameter to [affine_transform](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.affine_transform.html). By default we set it to `constant`, where voxels outside the image will be assumed to be zero. For a one-slice image this has obvious problems. You'll instead probably want `nearest`, where locations outside the bounds of the image will be mapped to the closest point in the image plane.

`conform` doesn't let you set it, but `resample_from_to` does.

Try:

```Python
img = nb.load('001_LA_ED.nii.gz')
new_aff = nb.affines.rescale_affine(img.affine, img.shape, (1, 1, 1))
vox_map = (img.shape, new_affine)
conformed = nb.processing.resample_from_to(img, vox_map, mode='nearest')
```

Note that this will leave your image in IRP orientation. Attempting to conform to RAS without changing the shape to be `(256, 1, 256)` will lose most of your data.

Now, you can reorient after resampling with:

```Python
reoriented = nb.as_closest_canonical(conformed)
```

A final note: Because you are upsampling without increasing the size of the image, you be losing data. You're going from a `440mm x 440mm x 1mm` field of view to a `256mm x 256mm x 1mm` field of view. `rescale_affine` will preserve the location of the central voxel, so this might be okay, but if you want the whole field-of-view, reoriented to RAS, I would do:

```Python
img = nb.load('001_LA_ED.nii.gz')

# Calculate new shape based on field-of-view, keeping non-spatial dimensions unchanged
fov = np.array(img.shape[:3]) * img.header.get_zooms()[:3]
new_shape = tuple(np.maximum(fov.astype(int), 1)) + img.shape[3:]

new_affine = nb.affines.rescale_affine(img.affine, new_shape[:3], (1, 1, 1))
conformed = nb.processing.resample_from_to(img, (new_shape, new_affine), mode='nearest')
reoriented = nb.as_closest_canonical(conformed)
```
