### ISSUE TITLE
Enabling GitHub discussions

### ISSUE THREAD

**Issue by ZviBaratz** [nipy/nibabel#1203]
@matthew-brett @effigies
What are your feelings regarding replacing the mailing list with GitHub Discussions as the preferred method for raising non-issues? 
Some things are neither explicit issues nor matters that necessarily justify a message in the NIPY mailing list. This issue is actually a decent example. The Discussions board also has the advantage of being more accessible than the mailing list, in terms of viewing and searching previous posts.

**Comment by matthew-brett** [comment]
I'd need a fair bit of persuading, because I've seen quite a few projects try it, and get bored, and switch back to whatever they were using before.  Scikit-image most recently.   Is there a project you know that's making good us of them?

**Comment by ZviBaratz** [comment]
I had a feeling you'd say that. I think there are a few projects making good use of it (e.g., [bokeh](https://github.com/bokeh/bokeh/discussions), [scikit-learn](https://github.com/scikit-learn/scikit-learn/discussions), [flaml](https://github.com/microsoft/FLAML/discussions), at least from my impression). IMO, there is something far less intimidating about opening a discussion compared with mailing a long mailing list or opening an issue. Email has become a somewhat formal means of communication, and not everything fits as an issue. As a user of a package as complex as nibabel you don't even necessarily know whether a problem you're facing is an issue or your own mistake. A discussion board serves as a less formal middle ground, where people can feel more free to participate, float ideas, ask for help (and convert to an issue or create an issue referencing the discussion, if required), etc.

**Comment by effigies** [comment]
My concern would be that it would be easy to forget about and not really use ourselves, and then users start asking questions and not getting help there because I'm used to looking in issues. Right now, I kind of expect people to use Neurostars, which has an existing cohort of competent responders without the pressure of email.

If you're interested in committing to be at least moderately responsive there, we could try it out; and if users start taking on answering each others' questions, cool, maybe it can grow. I don't think I have the time to make any commitments at the moment.

**Comment by ZviBaratz** [comment]
I definitely don't mind keeping an eye on it. However, for the sake of the users, most technical questions will probably be forwarded through a mention to you two 😅

**Comment by effigies** [comment]
@ZviBaratz https://github.com/nipy/nibabel/discussions/1215

Let's see how it goes.

**Comment by ZviBaratz** [comment]
Should we announce we're giving the discussions board a go on the mailing list? Perhaps also on Neurostars?

**Comment by effigies** [comment]
Go for it.
