### ISSUE TITLE
parrec2nii datatype output

### ISSUE THREAD

**Issue by cccbauer** [nipy/nibabel#321]
Hi Matthew,

 the parrec2nii is working fine! however, when we are trying to use the nifi output with another software, we have another issue :(  the software just takes in nifi files that are of data type short or 4, which is a signed 16-bit integer. Does this make sense? The current nifti output from parrec2nii is data type double or 64.
My question: is there a parameter I could change so the output nifti becomes a type 4 or do you have to hard code this?

thanks

clemens

**Comment by matthew-brett** [comment]
Sorry - you caught me while traveling across the atlantic.

I guess your par / rec data has different scaling per slice or volume, so the output volume needs to encode this, and uses floating point.

The easiest thing to do is make a little script to finish up the conversion, that does this:

```
img = nib.load('converted.nii')
img.set_data_dtype(np.int16)
nib.save(img, 'converted_int16.nii')
```

Does that work?

**Comment by satra** [comment]
@matthew-brett - i'm trying to help clemens get this working, but here is the issue. 

this saves the data as dtype = int16, but scl_slope and scl_interp are non-zero. what we need is the data to be int16, so that it doesn't get scaled. so i can do this:

```python
img = nb.load(filename)
data = img.get_data()
if data.max() < 2**16 and data.min() >= 0:
    nb.Nifti1Image(data.astype(np.int16), img.affine, img.header).to_filename(fileout)
else:
    raise ValueError('data range cannot be accommodated in 16-bit format')
```

we need this because our realtime tools expect shorts.

**Comment by matthew-brett** [comment]
If you really need int16 without scaling, I think you will have to cast the data yourself - like your example.  Does that not work for you?

**Comment by satra** [comment]
@matthew-brett - my example works, but is was hoping (similar to the mailing list discussion) for a way to preserve the native datatype through the process. so if the parrec2nifti reader read in a short it should not convert to float and write out a float in a short dtype. i.e. it should, like dicoms, preserve the native data type of the scanner even in the nifti file.

in the example that clemens shared with me, the data could easily fit an int16 (max was 3500), which is what it was being stored as, but scl_slope/inter was non-zero. so when the readers read it in, it converted it to float. is there a reason for the scaling factors to be non-zero, when the data can fit the underlying dtype?

this line `img.set_data_dtype(np.int16)` does not result in a changing of the data itself or changing the scale factors to 1/0, and i believe that's why clemens' original attempt didn't work. shouldn't `img.set_data_dtype` change the scale factors and map the data to the requested type?

**Comment by matthew-brett** [comment]
If your image has (in the PAR header) non-default scaling, this gets written into the output header.

If you don't care about the scalefactors, you can always load the image and wipe them out in the header and save the image again.

You can also use `img.dataobj.get_unscaled()` to get the raw data.

`set_data_dtype` sets the output dtype, but (by default) lets the image work out the scalefactors that best represent the image data when converted to the given datatype.

Or am I not understanding your question?

**Comment by cccbauer** [comment]
Hi Matthew, HI Satra,

here are some par/rec files as they come form the scanner if you need them! this ones don't have th phase images.

https://www.dropbox.com/s/1d8i68nwr7qqrp9/NoPhaseParRecs.zip?dl=0


thanks for all the help!
clemens

**Comment by satra** [comment]
@matthew-brett - i'll check the par/rec files clemens provided.

> set_data_dtype sets the output dtype, but (by default) lets the image work out the scalefactors that best represent the image data when converted to the given datatype.

this is the part i didn't understand. a 16-bit int could easily store the data without scaling, yet it is currently being stored with scaling, following this code you had asked clemens to use:

> ```python
img = nib.load('converted.nii')
img.set_data_dtype(np.int16)
nib.save(img, 'converted_int16.nii')
```
it turns out that if neither `slope` nor `inter` is `nan`, then `nb.Nifti1Image.to_file_map` does not change the scale factors even if datatype is changed. this could be a potential bug, i'll have to check.

**Comment by satra** [comment]
@matthew-brett - is there a way to set scl_slope == 0 when writing out the nifti file?

@cccbauer - if that can be done then the following code will preserve the data type when read in as short.

```
img = nb.load('Dump-0000.par')
img2 = nb.Nifti1Image(img.get_data().astype(np.int16), img.affine, img.header)
img2.set_data_dtype(np.int16)
# sth to set scl_slope to zero
img2.to_filename('Dump-0000.nii')
```

**Comment by matthew-brett** [comment]
Let's say you load an image `img`.  It has non-default scale factors, and on-disk data type `int16`.  The intended output data is then a floating point array:

```
raw = img.dataobj.get_unscaled()
intended = raw * scale + inter
```

This is what you get from `img.get_data()`.  

Let's say now that you are saving the image to `int16`.  The image will take the floating point data (`intended` in the text above), and convert it to int16 by finding the slope and inter such that the output int16 values cover the whole range from -2**15 to 2**15-1.   This will very likely not be the original scalefactors.

I guess you were expecting that, on save, the image would realize that the initial data came from scaled int16, and so use those same scale factors in writing the image?   

If you set slope and inter manually before saving, then the image assumes you intended these exact values, and does not modify them, so the behavior you see is what I'd expect, but I can imagine that's not obvious.  We've discussed that a couple of times on the mailing list.

To set the scale and intercept to desired values, try:

```
img2.header['scl_slope'] = 0
img2.header['scl_inter'] = 0
```

**Comment by satra** [comment]
thanks @matthew-brett - that works beautifully. i tried doing this earlier, which generated errors. 

`img2.header.set_slope_inter(0, 0)`

@cccbauer - you should be good to go with this:

```
img = nb.load('Dump-0000.par')
img2 = nb.Nifti1Image(img.get_data().astype(np.int16), img.affine, img.header)
img2.set_data_dtype(np.int16)
img2.header['scl_slope'] = 0
img2.header['scl_inter'] = 0
img2.to_filename('Dump-0000.nii')
```

@matthew-brett - regarding this bit:

> I guess you were expecting that, on save, the image would realize that the initial data came from scaled int16, and so use those same scale factors in writing the image?

what i was expecting was rather incorrect, especially for np.int16, and biased by my siemens' priors that data are output as int16 from the scanner.

**Comment by effigies** [comment]
This looks resolved. Please reopen if there's anything actionable.
