### ISSUE TITLE
Coveralls config doesn't allow viewing source code coverage changes

### ISSUE THREAD

**Issue by bcipolli** [nipy/nibabel#331]
So, I submitted a PR and am getting a failure check because coveralls reports decreased code coverage. I want to fix this:
![image](https://cloud.githubusercontent.com/assets/4072455/8790934/99be1b28-2f08-11e5-8762-7e952f4ba2f5.png)

So I click on the source file to see the coverage changes. But, the repo root directory is not set properly, so I see:
![image](https://cloud.githubusercontent.com/assets/4072455/8790939/b2fb8a08-2f08-11e5-88a9-c866e91d42ec.png)

Not sure how to fix this. Spent about 20 mins trying to find an answer, but only found other people with the same question. Perhaps someone else has solved this before?

**Comment by Eric89GXL** [comment]
I've had this problem on other repos. Tried a lot of things (symlinks, etc.) and the only solution was to ensure `nosetests` (or `py.test`) was run from the `git` root directory, so it imported from the `src` path instead of the install path. This lead to splitting some builds into `install` version and some to `src` version testing.

In the meantime you can get coverage locally. Not as convenient, but looking at the files that have been touched can work okay.

**Comment by Eric89GXL** [comment]
It looks like there are some other workarounds I didn't try (https://github.com/lemurheavy/coveralls-public/issues/471), but I'm not sure it would work.

**Comment by bcipolli** [comment]
@Eric89GXL The link you found is one of the ones I found as well.. but couldn't figure out how to change the settings, even for repos that I own. Note that this is essentially the same as https://github.com/nipy/nipy/issues/311

In the meantime, how would I go about getting coverage locally?

**Comment by Eric89GXL** [comment]
`nosetests --with-coverage --cover-package=nibabel` should work. FYI you can look at what `.travis.yml` says the call should be is since it generates coverage reports (it's the same as what I wrote).

If you want it nicely annotated, I think you can do `--cov-html` as well.

You can also look at the report generated by the Travis bots, but that's a lot slower than running it on your own.
