### ISSUE TITLE
slope/intercept not visible

### ISSUE THREAD

**Issue by cni-md** [nipy/nibabel#480]
Hi,
I converted Philips Dicom images of a fieldmap with dcm2niix to nifti. Unfortunately the order of mag/phs is not predictable. I thought the json file from heudiconv gives me a hint but this is not the case. Therefore, I have to analyse the nifti files.

fslhd phase.nii says that I have a usefull intercept:
scl_slope      0.106186
scl_inter      -217.391312

loading the same file with nibabel ('2.1.0dev')
data = nib.load('phase.nii')
print data.header
scl_slope       : nan
scl_inter       : nan

Jörg

**Comment by matthew-brett** [comment]
RIght - I'm afraid nibabel resets the slope and intercept when you load from disk.  It does this so that you know that the slope / intercept will, by default, be rewritten on save.   You can set the slope and intercept directly if you want.

To get the loaded slope and intercept look in `img.dataobj.slope` and `img.dataobj.inter`.

**Comment by cni-md** [comment]
Thank's a lot. That's what I am was looking for.
