### ISSUE TITLE
Question for reading 'lh.thickness.fwhm20.fsaverage.mgh' with nibabel.freesurfer.mghformat 

### ISSUE THREAD

**Issue by anbai106** [nipy/nibabel#511]
Hello, nibabel experts:
I have a question as described in the title, I want to read the thickness information from the output of Freesurfer, and I checked out the documentation from nibabel: 
[http://nipy.org/nibabel/reference/nibabel.freesurfer.html#mghimage](url)
I tried like this: 
`from nibabel.freesurfer.mghformat import MGHImage, MGHHeader

from nibabel.freesurfer.io import read_morph_data
import nibabel as nib
from nibabel.loadsave import read_img_data
from nibabel.freesurfer.mghformat import load
test = load('lh.thickness.fwhm20.fsaverage.mgh')
test1 = MGHHeader().data_from_fileobj('lh.thickness.fwhm20.fsaverage.mgh')
data = MGHImage('lh.thickness.fwhm20.fsaverage.mgh')`

But the results are not correct, I am a little confused about the three classes that you defined in the documentation, **_MGHHeader, MGHImage, Load_**, can you help me to clarify them a little, i know that if we want to read just **_?h.thickness_**, we can just use **_read_morph_data_** function, if you can give some example in the documentation, that would be great:)

Really hope to hear from you.

Thanks in advance
Hao

**Comment by effigies** [comment]
I'm not sure what you mean by "the results are not correct". Do you mean `test`, `test1` and `data` don't have the same contents?

Generally speaking, the way to load any file in nibabel is: `nib.load(fname)`.

```Python
from nibabel.freesurfer.mghformat import load
test = load('lh.thickness.fwhm20.fsaverage.mgh')
```

This should also work; it just forces `MGHImage` rather than detecting. The `.mgh` extension will get you here using `nibabel.load`.

```Python
test1 = MGHHeader().data_from_fileobj('lh.thickness.fwhm20.fsaverage.mgh')
```

This shouldn't work, since `'lh.thickness.fwhm20.fsaverage.mgh'` is a path, not an open file-like object.

```Python
data = MGHImage('lh.thickness.fwhm20.fsaverage.mgh')`
```

This  shouldn't work, either, since `MGHImage()` takes a data object, not a string, as its first parameter.

**Comment by anbai106** [comment]
Thanks for your rapid reply, no, I mean I tried some methods from the three classes, but none of them is what i want, basically, I want to read 'lh.thickness.fwhm20.fsaverage.mgh' as an array whose shape is (163842, 1, 1), with:
`from nibabel.freesurfer.mghformat import load
test = load('lh.thickness.fwhm20.fsaverage.mgh')`
This gave me the mgh image instance, but not the array data itself, and I dont know how to get it after i load the mgh file, here is the output of test:

> <class 'nibabel.freesurfer.mghformat.MGHImage'>
data shape (163842, 1, 1)
affine: 
[[ -1.00000000e+00   0.00000000e+00   0.00000000e+00   8.19210000e+04]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00  -5.00000000e-01]
 [  0.00000000e+00  -1.00000000e+00   0.00000000e+00   5.00000000e-01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
metadata:
<class 'nibabel.freesurfer.mghformat.MGHHeader'>
Dims: (163842, 1, 1)
MRI Type: MRI_FLOAT
goodRASFlag: 1
delta: [ 1.  1.  1.]
Mdc: 
[[-1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]
Pxyz_c: [ 0.  0.  0.]
mrparms: [ 0.  0.  0.  0.]

More generally, I am confused by some points in the documentation, 

1) 
> data_from_fileobj(fileobj)
> Read data array from fileobj
> 
> Parameters:	
> fileobj : file-like
> Must be open, and implement read and seek methods
> 
what does this mean read and seek methods ???

2) what is a **_fileobj, file-like_** object?

**Comment by anbai106** [comment]
Thanks for your rapid reply, 
`from nibabel.freesurfer.mghformat import load
test = load('lh.thickness.fwhm20.fsaverage.mgh')`
test returns me the MGH instance, but I dont know how to get the array data, here is the output of test:

> <class 'nibabel.freesurfer.mghformat.MGHImage'>
data shape (163842, 1, 1)
affine: 
[[ -1.00000000e+00   0.00000000e+00   0.00000000e+00   8.19210000e+04]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00  -5.00000000e-01]
 [  0.00000000e+00  -1.00000000e+00   0.00000000e+00   5.00000000e-01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]
metadata:
<class 'nibabel.freesurfer.mghformat.MGHHeader'>
Dims: (163842, 1, 1)
MRI Type: MRI_FLOAT
goodRASFlag: 1
delta: [ 1.  1.  1.]
Mdc: 
[[-1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]
Pxyz_c: [ 0.  0.  0.]
mrparms: [ 0.  0.  0.  0.]

>

**Comment by effigies** [comment]
Oh, I see. To get the data from an image, use:

```Python
img = nib.load(filename)
data = img.get_data()
```

As a rule, you shouldn't be playing with `data_from_fileobj`. That's a function that, given an open filehandle, retrieves the data in a way that is image specific. While it's not a private function, it's basically plumbing.

The way to read the documentation here is

```
parameter : type
description
```

So that's saying that `fileobj` must be like a Python `file` instance, insofar as it implements the `read` and `seek` methods.

P.S. Edited your post slightly for formatting.

**Comment by anbai106** [comment]
Thanks so much, before i used nib.load and get_data for nii images, but this time i deal with .mgh, and did think to use the same func....

Thanks again:)
