### ISSUE TITLE
Nibabel 2.3 freesurfer.read_annot() breaks backwards compatibility

### ISSUE THREAD

**Issue by christianbrodbeck** [nipy/nibabel#649]
Some .annot files have become unreadable since nibabel 2.3, with the error below:

```
In [22]: nibabel.freesurfer.read_annot('rh.fmri-tmean-25.annot')
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-22-c6989d89b74f> in <module>()
----> 1 nibabel.freesurfer.read_annot('rh.fmri-tmean-25.annot')

/Users/christian/Code/nibabel/nibabel/freesurfer/io.pyc in read_annot(filepath, orig_ids)
    391         mask = labels != 0
    392         labels[~mask] = -1
--> 393         labels[mask] = ord[np.searchsorted(ctab[ord, -1], labels[mask])]
    394     return labels, ctab, names
    395 

IndexError: index 1 is out of bounds for axis 1 with size 1

In [23]: 
```

I think I traced the problem to a change in the way the label ids (`ctab[:, 4]`) are calulated:  now it is 
```
    bitshifts = 2 ** np.array([[0], [8], [16], [24]], dtype=rgba.dtype)
    return rgba.dot(bitshifts)
```
previously it used to be the equivalent of 
```
    bitshifts = 2 ** np.array([[0], [8], [16]], dtype=rgba.dtype)
    return rgba[:, :3].dot(bitshifts)
```
So older files have different label IDs ... Not sure what the proper way to fix this is, revert the use of alpha in label IDs? but that would probably break compatibility with files saved with nibabel 2.3...

Here is a file that breaks: https://drive.google.com/file/d/11w6KPjfQdD0AliNxE_YP4pQNweX3Xgvk/view?usp=sharing for files with multiple labels it does not break, but I suspect label order might be shifted.

**Comment by pauldmccarthy** [comment]
Hi @christianbrodbeck, I understood the previous behaviour (ignoring the alpha value) to be a bug - the new implementation mirrors what is done in the only real reference that we have, which is the [freesurfer source code](https://github.com/freesurfer/freesurfer/blob/dev/matlab/read_annotation.m).

But there is no formal specification for the `.annot` file format, which makes it difficult to know exactly how alpha values are supposed to be handled. 

 -  The [notes here](https://surfer.nmr.mgh.harvard.edu/fswiki/LabelsClutsAnnotationFiles#Annotation) suggest that alpha values in the colour table should be stored as 255-alpha
 - The [comment here](https://github.com/freesurfer/freesurfer/blob/dev/matlab/write_annotation.m#L49) suggests that alpha values (referred to as `flag`) are expected to always be 0!

But neither of these bits of information agree with [what is actually implemented](https://github.com/freesurfer/freesurfer/blob/dev/matlab/read_annotation.m#L173).

I'm wondering though, if it would make any sense to implement the first suggestion (interpreting the stored value as 255-alpha). This appears to fix the issue with your test file, and would also bring the implementation into alignment with both of the above points for the most common scenario, where `alpha == 255`.

Any thoughts?

**Comment by christianbrodbeck** [comment]
In the current implementation (using 32 bit integers) IDs can be negative (`255 * 2 ** 24` leads to overflow and thus negative IDs). Is that intentional?

With 2.3, existing freesurfer parcellation become nonsensical (all alpha=0), so I think the fourth value should definitely be interpreted as 255-alpha:
```
In [5]: l, c, n = read_annot('lh.aparc.annot')

In [8]: c
Out[8]: 
array([[      25,        5,       25,        0,  1639705],
       [      25,      100,       40,        0,  2647065],
       [     125,      100,      160,        0, 10511485],
       [     100,       25,        0,        0,     6500],
       [     120,       70,       50,        0,  3294840],
       [     220,       20,      100,        0,  6558940],
       [     220,       20,       10,        0,   660700],
       [     180,      220,      140,        0,  9231540],
       [     220,       60,      220,        0, 14433500],
       [     180,       40,      120,        0,  7874740],
...

In [11]: nibabel.__version__
Out[11]: '2.3.0'
```
 
Taking care of these two issues might fix most backwards compatibility issues. It might still distort labels with varying alpha values?

**Comment by pauldmccarthy** [comment]
Hey @christianbrodbeck (and @larsoner), sorry for the delay.

I *think* that the data type should be changed to `int32`, because this is how the [freesurfer matlab code reads in the rgba values](https://github.com/freesurfer/freesurfer/blob/dev/matlab/read_annotation.m#L131). So this will result in some IDs overflowing to become negative. But, to my knowledge, these IDs are an internal detail and are somewhat meaningless to the end user, so is it really a problem, or am I wrong about these IDs being meaningless?

The main issue is how to store the alpha values - there is conflicting information as to what to do (see [my earlier comment](https://github.com/nipy/nibabel/issues/649#issuecomment-405488346)). 

Storing and interpreting them as `255 - alpha` seems to solve the problems in #663 and in this issue, but given that there is no formal spec, and that I'm not even a freesurfer user, I'd appreciate some verification from somebody who uses these files regularly - does the fix at [pauldmccarthy/nibabel/rf/fix_fs_annot](https://github.com/pauldmccarthy/nibabel.git) work for you?

**Comment by larsoner** [comment]
> So this will result in some IDs overflowing to become negative.

That isn't quite what's happening here. There used to be IDs like 16777215 which are well within `int32` bounds that become -1 now.

> these IDs are an internal detail and are somewhat meaningless to the end user, so is it really a problem, or am I wrong about these IDs being meaningless?

Previously the IDs were all non-negative (and might be by the spec?). There is code in PySurfer that relied on that using `searchsorted`, and indeed even in `nibabel` you get an error reading one of these annot files because of this same assumption (see code snippet at the top).

For me the alpha issue is not so critical because it was probably wrong before, and it's easy enough to ignore. The 16777215 becoming -1 not only breaks `nibabel.read_annot` itself but, even in cases where it can succeed, this remapping can break downstream code.

**Comment by pauldmccarthy** [comment]
> That isn't quite what's happening here. There used to be IDs like 16777215 which are well within int32 bounds that become -1 now.

The ID is generated from the rgba values, That colour is stored as `[255, 255, 255, 255]`. If  we interpret the alpha as `1-alpha`, it would become `[255, 255, 255, 0]` which, when converted to an ID via `_pack_rgba`, will result in the expected value of 16777215.

> Previously the IDs were all non-negative (and might be by the spec?

It shouldn't matter whether the IDs are positive or negative, as long as the IDs generated from the RGBA are bitwise identical to the IDs stored alongside the structure names. Of course they will potentially look different in the `ctab` array in Python, because the values are now being interpreted as signed 32 bit integer, rather than unsigned. But as long as we interpret all IDs in the same way (as either signed or unsigned), it shouldn't matter. 

The "spec" is a [bunch of matlab code and inline comments](https://github.com/freesurfer/freesurfer/blob/dev/matlab/read_annotation.m), and [some notes by Graham Wideman](https://surfer.nmr.mgh.harvard.edu/fswiki/LabelsClutsAnnotationFiles#Annotation), which don't agree with each other on some points. 

The [implementation in nibabel 2.2.2] was (IMO) buggy - it [forced all alpha values to 255](https://github.com/nipy/nibabel/blob/2.2.1/nibabel/freesurfer/io.py#L363), which is why all your alphas in #663 were output as 255, even though they are not stored as such in your file - as stored in the file, your first few colours are:
```
[     255,      255,      255,      255],
[      63,        5,      255,      0],
[      54,      103,      129,      0]
``` 

In #592, I was trying to fix this (so we can actually store alpha values), and to bring the `nibabel` implementation more inline with the freesurfer implementation.

But, because there is no proper specification, and disagreement between the matlab code, the comments, and GW's notes, I didn't know what to do with the alpha values.

> There is code in PySurfer that relied on that using searchsorted, and indeed even in nibabel you get an error reading one of these annot files because of this same assumption (see code snippet at the top).

The call to `searchsorted` in `nibabel` (and I'm guessing in pysurfer too) is used to find the structure names that correspond to each colour. If you hadn't already discovered, the `.annot` file format is completely insane - you need to take the RGBA bytes, generate this *ID* (called the *annotation value* in [GW's useful notes](https://surfer.nmr.mgh.harvard.edu/fswiki/LabelsClutsAnnotationFiles#Annotation)), and then search through the name list to find the name with the same value. And that's how you figure out which colours correspond to which names.

Sorry, that got a little long winded. Crazy file formats get on my nerves. On [my branch](https://github.com/pauldmccarthy/nibabel/tree/rf/fix_fs_annot), `nibabel` no longer throws the errors you were getting in #663 - mind having a play with it?

**Comment by effigies** [comment]
@pauldmccarthy Perhaps we should email the mailing list to resolve these contradictions. It may be that what was once a flag became an alpha channel later, and that we should settle on the canonical representation.

And is there any problem in principle of switching to `uint32`? They are reading single bytes into integers, and thus nothing should end up being negative except when the first bit of `alpha` is 1... Given that the internal representation is kind of irrelevant, as long as it's non-negative, this seems safe.

**Comment by pauldmccarthy** [comment]
Hey @effigies - exactly - it shouldn't matter whether we use `int32` or `uint32`, as long as the internal representation is consistent.

Which email list? I'm completely clueless about freesurfer for the most part :)

**Comment by effigies** [comment]
https://mail.nmr.mgh.harvard.edu/mailman/listinfo/freesurfer

**Comment by larsoner** [comment]
> It shouldn't matter whether the IDs are positive or negative, as long as the IDs generated from the RGBA are bitwise identical to the IDs stored alongside the structure names. Of course they will potentially look different in the ctab array in Python, because the values are now being interpreted as signed 32 bit integer, rather than unsigned. But as long as we interpret all IDs in the same way (as either signed or unsigned), it shouldn't matter.

That sems true for internal `nibabel` consistency/code/IO round-trips. But for packages that relied on the IDs having certain properties (non-negativity in this case) it's problematic.

On your new branch, nibabel can read the file but now only the first entry is non-negative:
```
[[     255      255      255        0 16777215]
 [      63        5      255      255   -64193]
 [      54      103      129      255 -8296650]]
```
The negative values are `2 ** 24` off from the old values. In this sense it seems like "ensuring all positive" (modulo 2 ** 24) would fix things.

**Comment by larsoner** [comment]
> So, unless I've understood things incorrectly (which is extremely possible), the IDs must change between nibabel pre-2.3, and post-2.3.

I can change PySurfer to deal with the negative values. I agree it's better long term to have consistency with Freesurfer's implementation (`int32`). It's probably worth putting in the release notes that these IDs have changed and now can be non-negative, though.

**Comment by pauldmccarthy** [comment]
I've [dropped a message](https://www.mail-archive.com/freesurfer@nmr.mgh.harvard.edu/msg59516.html) on the freesurfer list - hopefully somebody will enlighten us about these mysterious alpha values.

@larsoner - yes, a note in the release notes would have been useful for this. In my next PR (which I'll hold off on until we hear back from the FS people), I'll make sure to add a note about this.

I'm also off on holiday from tomorrow. without laptop, for the next 10 or so days - sorry!

**Comment by larsoner** [comment]
Not a problem, I have a workaround that does the wrap-to-positive (future compatible), ID fixing (current version compatible), and alpha fixing (past version compatible) working now I think.

**Comment by effigies** [comment]
Okay, I've spent a little bit of time trying to wrap my head around this.

In the FreeSurfer source. The fourth column on disk is transparency, and is stored as alpha. [CTABreadFromBinaryV1](https://github.com/freesurfer/freesurfer/blob/8b88b346483ab97daeee45623953cdcf137f18ca/utils/colortab.c#L636-L637)/[CTABreadFromBinaryV2](https://github.com/freesurfer/freesurfer/blob/8b88b346483ab97daeee45623953cdcf137f18ca/utils/colortab.c#L790-L791):

```C
    t = freadInt(fp);
    ct->entries[structure]->ai = 255 - t; /* alpha = 255-trans */
```

There's nothing in the IO that enforces label values = `(255 - alpha) * 2^24 + blue * 2^16 + green * 2^8 + red`, and nothing that I can see that requires label values to be positive or non-negative.

I also see no evidence in the source that the alpha channel is used at all to create or interpret values:

[CTABrgb2Annotation](https://github.com/freesurfer/freesurfer/blob/8b88b346483ab97daeee45623953cdcf137f18ca/utils/colortab.c#L1363-L1368):
```C
int CTABrgb2Annotation(int r, int g, int b)
{
  int annotation;
  annotation = (b << 16) + (g << 8) + r;
  return (annotation);
}
```
[CTABfindAnnotation](https://github.com/freesurfer/freesurfer/blob/8b88b346483ab97daeee45623953cdcf137f18ca/utils/colortab.c#L1434-L1450):
```C
int CTABfindAnnotation(COLOR_TABLE *ct, int annotation, int *index)
{
  int r, g, b;
  int result;


  if (NULL == ct) ErrorReturn(ERROR_BADPARM, (ERROR_BADPARM, "CTABfindAnnotation: ct was NULL"));
  if (NULL == index) ErrorReturn(ERROR_BADPARM, (ERROR_BADPARM, "CTABfindAnnotation: output parameter was NULL"));


  /* Separate the annotation into colors and then find the color. */
  r = annotation & 0x0000ff;
  g = (annotation >> 8) & 0x0000ff;
  b = (annotation >> 16) & 0x0000ff;


  result = CTABfindRGBi(ct, r, g, b, index);


  return (result);
}
```

I can only conclude that the documentation is actually wrong. I would propose that we do the following:

1. Continue returning the transparency values, not the alpha channels. Just document that it is transparency, and should be interpreted as `alpha = 255 - transparency`.
2. Change `_pack_rgba` to `_pack_rgb`.

Would this cause problems anybody can foresee? Would it actually fix anything?

**Comment by larsoner** [comment]
That seems to have "fixed" the IDs to make them what they were before, and the second-to-last channel looks properly defined as `255 - alpha`. So I'm happy with it!

**Comment by pauldmccarthy** [comment]
@effigies thanks for sorting this out!
