### ISSUE TITLE
Echo Time Slice - Par Rec 

### ISSUE THREAD

**Issue by gattia** [nipy/nibabel#985]
Hi, 

nibabel sorts images based on slice as well as secondary outcomes (e.g., echo time TE). Is this information (the actual TE (ms)) stored in the header anywhere? 

Thanks! 

Anthony.

**Comment by gattia** [comment]
As I play around with the data, I noted that the header has a property `image_defs` that appears to be the length of the slices (n_slices * n_echos) and has 41 values (or arrays, or strings) per slice. So, I am guessing that this is all of the information that I am looking for. However, I cant find where exactly each of these 41 values are defined. 

I'll look around some more and report back if I find the information that I am looking for.

**Comment by gattia** [comment]
So, looks like there is a function: 

`nib_image.header.get_def()`

If you pass this a string it will return the values for that parameter for each slice. The Ones that I was looking for were: 

`echo number`
`echo_time`

e.g.,
`nib_image.header.get_def('echo_time')`

returns the echo times for each of the slices. This solves my problem. However, I couldn't find anywhere to actually get the list of potential options (e.g., echo_time). I had to find this one from the PAR header manually.

Is there a function to get this list automatically? Or to get the list of the names of the volumes in the `image.header.image_defs`.

**Comment by effigies** [comment]
If we look at the definition for `get_def()`:

https://github.com/nipy/nibabel/blob/a7e94d6394b12424a3b0f51b1cd2c9ce39aac6cd/nibabel/parrec.py#L841-L844

It looks like these are named fields in a numpy array that you could query with `img.header.image_defs.dtype.names`. A bit of following references shows:

https://github.com/nipy/nibabel/blob/a7e94d6394b12424a3b0f51b1cd2c9ce39aac6cd/nibabel/parrec.py#L350-L354

And we can see:

https://github.com/nipy/nibabel/blob/a7e94d6394b12424a3b0f51b1cd2c9ce39aac6cd/nibabel/parrec.py#L219-L270

So that seems to be the set for each version.

**Comment by gattia** [comment]
Thanks @effigies! This is perfect and exactly what I was looking for. 

It might be useful to include this somewhere in the documentation. I could open another issue, or potentially look at making a pull request. This seems like useful/necessary information for many purposes (e.g., Im making T2 maps from multi-echo sequences) and while I totally follow what you wrote/how you got to it, even finding/realizing that `.get_def()` did what it did was a wild guess.
