### ISSUE TITLE
Question about H5 file to MGZ file

### ISSUE THREAD

**Issue by OGWang126** [nipy/nibabel#992]
I used nibabel transfer mgz to h5 already, but failed to trans back to mgz and open it in freesurfer view. Here are my codes.
`import nibabel as nib

import numpy as np

import h5py

H5F = h5py.File("./mgzToH5.h5")

dataMatrix = np.array(H5F['data'])

nib.save(dataMatrix,'./test.mgz')
`
which method or func should I use? Or maybe I need to trans np.arry to Nifti1Image? Thanks a lot

**Comment by effigies** [comment]
Yes, you can't save a data array as an image directly. You need to create an image, which means you need an affine matrix. See [Array images](https://nipy.org/nibabel/nibabel_images.html#array-images) for the syntax. If you want an MGZ file, you can use `nib.MGHImage` instead of `nib.Nifti1Image`.

If you did not save the affine into your HDF5 file, then you'll probably want to find an existing image that has the same size and orientation as the data array and use its affine. e.g.,

```Python
import nibabel as nib
import numpy as np
import h5py

H5F = h5py.File("./mgzToH5.h5")
ref_img = nib.load("reference_image.mgz")

img = nib.MGHImage(np.array(H5F['data']), affine=ref_img.affine)

nib.save(img,'./test.mgz')
```

**Comment by OGWang126** [comment]
OMG!!! It's finally worked!! Thanks a lot!
